# site settings
title: HOME
# subtitle: ZAINEB PENWALA
email: zenp1520@gmail.com
description: welcome to my techie-foodie world
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Zaineb Penwala
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
github_url: https://github.com/zainebpenwala
linkedin_url: https://www.linkedin.com/in/zaineb-penwala-67322116a
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
